# Generated by Django 5.2.13 on 2026-04-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaewhoncost', '0002_increase_quantity_decimal_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
