# Generated by Django 5.2.13 on 2026-04-30 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaewhoncost', '0003_increase_price_decimal_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=100)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'รอชำระ'), ('paid', 'ชำระแล้ว'), ('partial', 'ชำระบางส่วน')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='jaewhoncost.branch')),
            ],
            options={
                'verbose_name': 'การจัดซื้อ',
                'verbose_name_plural': 'การจัดซื้อ',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quantity_purchased', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('effective_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='jaewhoncost.ingredient')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_histories', to='jaewhoncost.purchase')),
            ],
            options={
                'verbose_name': 'ประวัติราคาวัตถุดิบ',
                'verbose_name_plural': 'ประวัติราคาวัตถุดิบ',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jaewhoncost.ingredient')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jaewhoncost.purchase')),
            ],
            options={
                'verbose_name': 'รายการจัดซื้อ',
                'verbose_name_plural': 'รายการจัดซื้อ',
                'unique_together': {('purchase', 'ingredient')},
            },
        ),
    ]
