# Generated by Django 6.0.4 on 2026-05-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaewhoncost', '0004_add_purchase_and_pricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='overhead_delivery',
            field=models.DecimalField(decimal_places=2, default=17.01, max_digits=10, verbose_name='ค่าจัดส่ง'),
        ),
        migrations.AddField(
            model_name='setting',
            name='overhead_depreciation',
            field=models.DecimalField(decimal_places=2, default=1.8, max_digits=10, verbose_name='ค่าเสื่อมราคา'),
        ),
        migrations.AddField(
            model_name='setting',
            name='overhead_labor',
            field=models.DecimalField(decimal_places=2, default=16.2, max_digits=10, verbose_name='ค่าแรงงาน'),
        ),
        migrations.AddField(
            model_name='setting',
            name='overhead_marketing',
            field=models.DecimalField(decimal_places=2, default=1.8, max_digits=10, verbose_name='ค่าการตลาด'),
        ),
        migrations.AddField(
            model_name='setting',
            name='overhead_rent',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=10, verbose_name='ค่าเช่า'),
        ),
        migrations.AddField(
            model_name='setting',
            name='overhead_utilities',
            field=models.DecimalField(decimal_places=2, default=4.8, max_digits=10, verbose_name='ค่าสาธารณูปโภค'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
