# Generated by Django 5.2.13 on 2026-05-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaewhoncost', '0007_owner_logo_alter_branch_id_alter_ingredient_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'วัตถุดิบ', 'verbose_name_plural': 'วัตถุดิบ'},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
