# Generated by Django 5.2.13 on 2026-05-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaewhoncost', '0008_add_sort_order_to_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'เมนู', 'verbose_name_plural': 'เมนู'},
        ),
        migrations.AddField(
            model_name='menu',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
